[package]
name = "meh"
version = "0.1.0"
edition = "2021"
description = "Michael's Error Handling library to make it hard to write bad error types"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
trybuild = "1.0"
